In [56]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier

In [57]:
headernames=["Age","Year","No.-of-node ","Survival-Status"]

In [58]:
dataset = pd.read_csv('haberman.data',names=headernames)

In [59]:
dataset.shape

(306, 4)

In [60]:
dataset.head()

Age  Year  No.-of-node   Survival-Status
0   30    64             1                1
1   30    62             3                1
2   30    65             0                1
3   31    59             2                1
4   31    65             4                1

In [61]:
array=dataset.values
x=array[:,:-1]
y=array[:,3]


In [62]:
thismodel=KNeighborsClassifier()
print("\nThe model selected is",thismodel)
print("\nThe parameters of the model are \n\n",thismodel.get_params())



The model selected is KNeighborsClassifier()

The parameters of the model are 

 {'algorithm': 'auto', 'leaf_size': 30, 'metric': 'minkowski', 'metric_params': None, 'n_jobs': None, 'n_neighbors': 5, 'p': 2, 'weights': 'uniform'}


In [77]:
thismodel.fit(x,y)

KNeighborsClassifier()

In [84]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20)

In [85]:
y_pred=thismodel.predict(x_test)
print(x_test)
print(y_pred)

[[49 62  1]
 [64 65 22]
 [55 68 15]
 [56 66  2]
 [59 64  0]
 [47 58  3]
 [68 67  0]
 [61 62  5]
 [49 63  0]
 [47 67  0]
 [60 65  0]
 [72 67  3]
 [43 58 52]
 [60 61  1]
 [54 60 11]
 [53 61  1]
 [41 65  0]
 [48 67  7]
 [52 66  4]
 [57 64  9]
 [50 61  0]
 [43 64  0]
 [57 61  0]
 [34 59  0]
 [64 66  0]
 [54 69  7]
 [57 64  0]
 [52 69  0]
 [45 67  1]
 [59 67  3]
 [62 62  6]
 [50 61  0]
 [65 62 22]
 [42 63  1]
 [55 66 18]
 [33 60  0]
 [67 61  0]
 [39 63  4]
 [47 66 12]
 [57 62 14]
 [66 61 13]
 [65 64  0]
 [66 58  0]
 [54 62  0]
 [72 64  0]
 [41 64  0]
 [77 65  3]
 [58 61  1]
 [76 67  0]
 [60 59 17]
 [69 65  0]
 [45 64  0]
 [66 58  0]
 [58 61  2]
 [53 58  4]
 [70 58  0]
 [71 68  2]
 [50 59  2]
 [42 59  2]
 [34 67  7]
 [63 60  1]
 [38 60  0]]
[1 2 2 1 1 1 1 1 1 1 1 1 2 1 2 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1
 1 2 2 2 1 1 1 1 1 1 1 1 2 1 1 1 1 2 1 1 1 1 1 1 1]


In [86]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           1       0.77      0.93      0.84        43
           2       0.70      0.37      0.48        19

    accuracy                           0.76        62
   macro avg       0.73      0.65      0.66        62
weighted avg       0.75      0.76      0.73        62

